### ISSUE TITLE
Apache does not work

### ISSUE THREAD

**Issue by getsolveit** [amooma/GS5#306]
Apache will not start with new Images.

Starting web server: apache2apache2: Syntax error on line 244 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/passenger.load: Cannot load /var/lib/gs5/.rvm/gems/ruby-1.9.3-p448/gems/passenger/ext/apache2/mod_passenger.so into server: /var/lib/gs5/.rvm/gems/ruby-1.9.3-p448/gems/passenger/ext/apache2/mod_passenger.so: cannot open shared object file: No such file or directory
Action 'start' failed.
The Apache error log may have more information.
 failed!

**Comment by jpawlowski** [comment]
fixed by https://github.com/amooma/GBE/commit/8d0c6f69b197b03d3502f58cc0a8797c43a6be01

**Comment by getsolveit** [comment]
Please re-open it, the bug is back, with the latest 3 develp builds from the amooma website.

**Comment by jpawlowski** [comment]
no need to re-open, the fix still persists.
the dev build were actually not the latest ones.
