### ISSUE TITLE
tenant phones have no address books

### ISSUE THREAD

**Issue by duebel-** [amooma/GS5#310]
/config_snom/phoneId/sipaccountId/phone_book.xml gives:

```
<!-- SipAccount not found -->
```

/config_yealink/phoneId/sipaccountId/phone_book.xml gives:
We're sorry, but something went wrong.... 
production.log:

```
NoMethodError (undefined method `phone_books' for #<Class:0xadf1290>):
  app/controllers/config_yealink_controller.rb:197:in `phone_book'
```

**Comment by spag** [comment]
Fixed in commit 3893e50c2b27cf8b3958ed1b36697ab66a7f70b5

**Comment by duebel-** [comment]
I can confirm /config_snom/phoneId/sipaccountId/phone_book.xml is fixed.

**Comment by duebel-** [comment]
But /config_yealink/phoneId/sipaccountId/phone_book.xml is not fixed. Please reopen.

Error is:

```
`NoMethodError (undefined method `phone_books' for #<Class:0xa47890c>):
  app/controllers/config_yealink_controller.rb:220:in `phone_book'
```

**Comment by duebel-** [comment]
Fix:

```
diff --git a/app/controllers/config_yealink_controller.rb b/app/controllers/config_yealink_controller.rb
index e2d673a..524eb32 100644
--- a/app/controllers/config_yealink_controller.rb
+++ b/app/controllers/config_yealink_controller.rb
@@ -199,7 +199,6 @@ class ConfigYealinkController < ApplicationController
     @phone_books = Array.new()
     tenant = nil
     phone_book_ids = {}
-    if @phone.phoneable.class == User
       @phone.phoneable.phone_books.each do |phone_book|
         if @phone_books.count >= MAX_PHONEBOOK_ENTRIES
           break
@@ -211,9 +210,8 @@ class ConfigYealinkController < ApplicationController
         @phone_books << {:name => phone_book.name, :url => "#{base_url}/#{phone_book.id}/phone_book.xml"}
         phone_book_ids[phone_book.id]
       end
+    if @phone.phoneable.class == User
       tenant = @phone.phoneable.current_tenant
-    elsif @phone.phoneable.class == Tenant
-      tenant = @phone.phoneable.class
     end

     if tenant
```

**Comment by spag** [comment]
tenant = @phone.phoneable.class -> tenant = @phone.phoneable
