### ISSUE TITLE
Asset issues / images not shown

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#5]
After a fresh installation some assets may not load or may not be available.
For instance

/assets/icons/phone-down-grey-32x.png
`No route matches [GET] "/assets/icons/phone-down-grey-32x.png"`

Precompilation task run successfully during first bootup according to /var/log/gemeinschaft/setup.log and /var/log/boot.
Changing from development to production environment shows a running installation, although graphics like the one mentioned are not shown

**Comment by wintermeyer** [comment]
Fixed by c8f3bc41866ca94119bcb1d3e04dbea6b93e86a8

**Comment by jpawlowski** [comment]
Sorry, it seems that didn't fix the problem :-(
File exists now but error persists.

**Comment by wintermeyer** [comment]
Should be fixed by 9c392982e2ba7eaeb237268e9299637a8f8b4c3a
