### ISSUE TITLE
Read database settings from .odbc.ini instead of database.yml

### ISSUE THREAD

**Issue by jpawlowski** [amooma/GS5#90]
Would it be possible to parse `/var/lib/freeswitch/.odbc.ini` for the database credentials instead of using GS5/config/database.yml?

This is the last redundant storage for database credentials (beside freeswitch.xml).

**Comment by wintermeyer** [comment]
Please upload an example odbc.ini file to this issue.

**Comment by jpawlowski** [comment]
```
[gemeinschaft]
Description  = MySQL database for Gemeinschaft
Driver       = /usr/lib/odbc/libmyodbc.so
SERVER       = localhost
PORT         = 3306
DATABASE     = gemeinschaft
OPTION       = 67108864
USER         = gemeinschaft
PASSWORD     = TyigBovyum6quaislujliceyctivFa
```

**Comment by wintermeyer** [comment]
I included it in af49b3390ce352297c3b601c69b6b0557a9ae01d . Please test it.

**Comment by jpawlowski** [comment]
This is the resulting error output from Apache Passenger (produces a 500er error):

```
[Fri Jan 11 19:36:52 2013] [notice] Apache/2.2.16 (Debian) Phusion_Passenger/3.0.17 mod_ssl/2.2.16 OpenSSL/0.9.8o configured -- resuming normal operations
/usr/bin/env: ruby: No such file or directory
/usr/bin/env: ruby: No such file or directory
/usr/bin/env: ruby: No such file or directory
/usr/bin/env: ruby: No such file or directory
[ pid=6382 thr=76129270 file=utils.rb:176 time=2013-01-11 19:37:04.317 ]: *** Exception SyntaxError in PhusionPassenger::ClassicRails::ApplicationSpawner ((erb):23: syntax error, unexpected keyword_else
; - else ; _erbout.concat "\nproducti...
        ^
(erb):33: syntax error, unexpected keyword_end
; - end ; _erbout.concat "\n"
       ^
(erb):34: syntax error, unexpected keyword_end
; - end ; _erbout.concat "\n\n# Warn...
       ^
(erb):44: syntax error, unexpected $end, expecting keyword_end
; _erbout.force_encoding(__ENCODING__)
                                      ^) (process 6382, thread #<Thread:0x91347ec>):
    from /var/lib/gs5/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/erb.rb:838:in `eval'
    from /var/lib/gs5/.rvm/rubies/ruby-1.9.3-p362/lib/ruby/1.9.1/erb.rb:838:in `result'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/railties-3.2.2/lib/rails/application/configuration.rb:115:in `database_configuration'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/railtie.rb:75:in `block (2 levels) in <class:Railtie>'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.2/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.2/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activesupport-3.2.2/lib/active_support/lazy_load_hooks.rb:26:in `on_load'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/activerecord-3.2.2/lib/active_record/railtie.rb:74:in `block in <class:Railtie>'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/railties-3.2.2/lib/rails/initializable.rb:30:in `instance_exec'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/railties-3.2.2/lib/rails/initializable.rb:30:in `run'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/railties-3.2.2/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/railties-3.2.2/lib/rails/initializable.rb:54:in `each'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/railties-3.2.2/lib/rails/initializable.rb:54:in `run_initializers'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/railties-3.2.2/lib/rails/application.rb:136:in `initialize!'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/railties-3.2.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /opt/GS5/config/environment.rb:5:in `<top (required)>'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/classic_rails/application_spawner.rb:222:in `require'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/classic_rails/application_spawner.rb:222:in `preload_application'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/classic_rails/application_spawner.rb:181:in `block in initialize_server'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/utils.rb:563:in `report_app_init_status'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/classic_rails/application_spawner.rb:174:in `initialize_server'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server.rb:204:in `start_synchronously'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server.rb:180:in `start'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/spawn_manager.rb:219:in `block (2 levels) in spawn_rails_application'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/spawn_manager.rb:214:in `block in spawn_rails_application'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
    from <internal:prelude>:10:in `synchronize'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
    from /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/passenger-3.0.17/helper-scripts/passenger-spawn-server:99:in `<main>'
[ pid=6395 thr=3044199280 file=ext/apache2/Hooks.cpp:884 time=2013-01-11 19:37:04.424 ]: Unexpected error in mod_passenger: Cannot spawn application '/opt/GS5': An error occured while spawning the application.
  Backtrace:
     (empty)
```

**Comment by wintermeyer** [comment]
You were too fast. I fixed it 30 seconds later. ;-)

**Comment by jpawlowski** [comment]
the new system update script was faster :dancers:

**Comment by jpawlowski** [comment]
Ok, just fixed the correct file path. But we still have an error:

```
Started GET "/" for 192.168.6.105 at 2013-01-11 19:52:18 +0100

ActiveRecord::StatementInvalid (Could not find table 'sessions'):
  activerecord (3.2.2) lib/active_record/connection_adapters/sqlite_adapter.rb:465:in `table_structure'
  activerecord (3.2.2) lib/active_record/connection_adapters/sqlite_adapter.rb:346:in `columns'
  activerecord (3.2.2) lib/active_record/connection_adapters/schema_cache.rb:12:in `block in initialize'
  activerecord (3.2.2) lib/active_record/model_schema.rb:228:in `yield'
  activerecord (3.2.2) lib/active_record/model_schema.rb:228:in `default'
  activerecord (3.2.2) lib/active_record/model_schema.rb:228:in `columns'
  activerecord (3.2.2) lib/active_record/model_schema.rb:237:in `columns_hash'
  activerecord (3.2.2) lib/active_record/session_store.rb:111:in `setup_sessid_compatibility!'
  activerecord (3.2.2) lib/active_record/session_store.rb:98:in `find_by_session_id'
  activerecord (3.2.2) lib/active_record/session_store.rb:306:in `block in get_session'
  activesupport (3.2.2) lib/active_support/benchmarkable.rb:50:in `silence'
  activerecord (3.2.2) lib/active_record/session_store.rb:305:in `get_session'
  rack (1.4.1) lib/rack/session/abstract/id.rb:246:in `load_session'
  actionpack (3.2.2) lib/action_dispatch/middleware/session/abstract_store.rb:47:in `block in load_session'
  actionpack (3.2.2) lib/action_dispatch/middleware/session/abstract_store.rb:55:in `stale_session_check!'
  actionpack (3.2.2) lib/action_dispatch/middleware/session/abstract_store.rb:47:in `load_session'
  rack (1.4.1) lib/rack/session/abstract/id.rb:130:in `load!'
  rack (1.4.1) lib/rack/session/abstract/id.rb:122:in `load_for_read!'
  rack (1.4.1) lib/rack/session/abstract/id.rb:64:in `has_key?'
  actionpack (3.2.2) lib/action_dispatch/middleware/flash.rb:258:in `ensure in call'
  actionpack (3.2.2) lib/action_dispatch/middleware/flash.rb:259:in `call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/cookies.rb:338:in `call'
  activerecord (3.2.2) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:443:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.2) lib/active_support/callbacks.rb:405:in `_run__925110338__call__641741659__callbacks'
  activesupport (3.2.2) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.2) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.2) lib/rails/rack/logger.rb:26:in `call_app'
  railties (3.2.2) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.2) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.1) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.2) lib/action_dispatch/middleware/static.rb:61:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.2) lib/rails/engine.rb:479:in `call'
  railties (3.2.2) lib/rails/application.rb:220:in `call'
  railties (3.2.2) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (3.0.17) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  passenger (3.0.17) lib/phusion_passenger/abstract_request_handler.rb:516:in `accept_and_process_next_request'
  passenger (3.0.17) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  passenger (3.0.17) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
  passenger (3.0.17) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `block in handle_spawn_application'
  passenger (3.0.17) lib/phusion_passenger/utils.rb:470:in `safe_fork'
  passenger (3.0.17) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
  passenger (3.0.17) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.17) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.17) lib/phusion_passenger/abstract_server.rb:180:in `start'
  passenger (3.0.17) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
  passenger (3.0.17) lib/phusion_passenger/spawn_manager.rb:219:in `block (2 levels) in spawn_rails_application'
  passenger (3.0.17) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  passenger (3.0.17) lib/phusion_passenger/spawn_manager.rb:214:in `block in spawn_rails_application'
  passenger (3.0.17) lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
  <internal:prelude>:10:in `synchronize'
  passenger (3.0.17) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (3.0.17) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
  passenger (3.0.17) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
  passenger (3.0.17) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  passenger (3.0.17) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.17) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.17) helper-scripts/passenger-spawn-server:99:in `<main>'


  Rendered /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/actionpack-3.2.2/lib/action_dispatch/middleware/templates/rescues/_trace.erb (2.6ms)
  Rendered /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/actionpack-3.2.2/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1.2ms)
  Rendered /var/lib/gs5/.rvm/gems/ruby-1.9.3-p362/gems/actionpack-3.2.2/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (9.3ms)
```

**Comment by wintermeyer** [comment]
I don't know what happens there. Is this production or development? Why does it mention the sqlite_adapter.rb when we use MySQL in production?

**Comment by jpawlowski** [comment]
I have no idea. It's the latest development build, just boot it up to see for yourself

**Comment by jpawlowski** [comment]
Stop. I know what happens, one moment.

**Comment by jpawlowski** [comment]
Hm, I fear the error persists. The password section still got overwritten from my script but now that I have corrected it with your password definitions the session error is still there....
